export interface GenreProps {
  title: string
  image: string
  color: string
}

export const GENRES: GenreProps[] = [
  {
    title: "Action",
    image: "/genre-images/action.webp",
    color: "#7F00FF",
  },
  {
    title: "Thriller",
    image: "/genre-images/thriller.jpg",
    color: "#4b0082",
  },
  {
    title: "Sci-Fi",
    image: "/genre-images/scifi.webp",
    color: "#0000FF",
  },
  {
    title: "Romance",
    image: "/genre-images/romance.webp",
    color: "#00FF00",
  },
  {
    title: "Crime",
    image: "/genre-images/crime.webp",
    color: "#008080",
  },
  {
    title: "Comedy",
    image: "/genre-images/comedy.webp",
    color: "#00FFFF",
  },
  {
    title: "Horror",
    image: "/genre-images/horror.webp",
    color: "#FFC0CB",
  },
  {
    title: "Comics",
    image: "/genre-images/comics.webp",
    color: "#FF0000",
  },
]

export const RECOMMENDED_MOVIES: Movie[] = [
  {
    genres: ["Action", "Crime", "Drama", "IMAX"],
    image: "http://image.tmdb.org/t/p/w500//qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    imdbId: 468569,
    movieId: 58559,
    rating: 4.220129171151776,
    tags: [
      "action",
      "action packed",
      "adaptation",
      "adapted from:comic",
      "adventure",
      "alter ego",
      "amazing cinematography",
      "anti-hero",
      "atmospheric",
      "awesome",
      "awesome soundtrack",
      "based on a comic",
      "based on comic",
      "batman",
      "best of 2005",
      "betrayal",
      "big budget",
      "brutality",
      "catastrophe",
      "cerebral",
      "chase",
      "cinematography",
      "clever",
      "comic book",
      "comic book adaption",
      "comics",
      "complex",
      "complex characters",
      "complicated",
      "cool",
      "corruption",
      "crime",
      "cult classic",
      "dark",
      "dark hero",
      "dark humor",
      "dc comics",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "drinking",
      "dynamic cgi action",
      "dystopia",
      "ensemble cast",
      "entertaining",
      "epic",
      "excellent",
      "excellent script",
      "exceptional acting",
      "exciting",
      "fast paced",
      "fight scenes",
      "fighting",
      "forceful",
      "franchise",
      "good",
      "good acting",
      "good action",
      "good sequel",
      "good soundtrack",
      "good versus evil",
      "graphic novel",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "great soundtrack",
      "greed",
      "grim",
      "gritty",
      "harsh",
      "highly quotable",
      "honest",
      "imdb top 250",
      "insanity",
      "intense",
      "interesting",
      "justice",
      "life philosophy",
      "loneliness",
      "long",
      "masterpiece",
      "melancholy",
      "mentor",
      "moral ambiguity",
      "morality",
      "movielens top pick",
      "murder",
      "mythology",
      "narrated",
      "nocturnal",
      "organized crime",
      "original",
      "original plot",
      "oscar",
      "oscar (best actor)",
      "oscar (best actress)",
      "oscar (best directing)",
      "oscar (best effects - visual effects)",
      "oscar (best picture)",
      "oscar (best supporting actor)",
      "oscar winner",
      "pg-13",
      "philosophy",
      "plot",
      "plot twist",
      "powerful ending",
      "psychological",
      "psychology",
      "quotable",
      "realistic",
      "redemption",
      "reflective",
      "revenge",
      "runaway",
      "sacrifice",
      "shallow",
      "social commentary",
      "special effects",
      "story",
      "storytelling",
      "stylish",
      "stylized",
      "super hero",
      "super-hero",
      "superhero",
      "superheroes",
      "suspense",
      "talky",
      "technology",
      "tense",
      "thought-provoking",
      "thriller",
      "torture",
      "transformation",
      "twists & turns",
      "unusual plot structure",
      "vengeance",
      "very good",
      "vigilante",
      "vigilantism",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weapons",
    ],
    title: "Dark Knight, The (2008)",
    tmdbId: 155.0,
  },
  {
    genres: ["Crime", "Horror", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    imdbId: 102926,
    movieId: 593,
    rating: 4.17705650958151,
    tags: [
      "action",
      "adaptation",
      "adapted from:book",
      "afi 100 (movie quotes)",
      "atmospheric",
      "based on a book",
      "based on book",
      "blood",
      "book",
      "books",
      "brilliant",
      "brutal",
      "brutality",
      "cannibalism",
      "cerebral",
      "character study",
      "chase",
      "cinematography",
      "classic",
      "claustrophobic",
      "clever",
      "complex",
      "complex characters",
      "complicated",
      "corruption",
      "creepy",
      "crime",
      "crime gone awry",
      "criterion",
      "cult classic",
      "cult film",
      "dark",
      "detective",
      "dialogue",
      "disturbing",
      "drama",
      "dramatic",
      "earnest",
      "eerie",
      "enigmatic",
      "entertaining",
      "excellent",
      "excellent script",
      "exceptional acting",
      "exciting",
      "fast paced",
      "fbi",
      "forceful",
      "frightening",
      "good",
      "good acting",
      "good soundtrack",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "gruesome",
      "hannibal lecter",
      "highly quotable",
      "horror",
      "identity",
      "imdb top 250",
      "insanity",
      "intellectual",
      "intelligent",
      "intense",
      "interesting",
      "investigation",
      "justice",
      "kidnapping",
      "macabre",
      "manipulation",
      "masterpiece",
      "mental illness",
      "mentor",
      "moral ambiguity",
      "murder",
      "mystery",
      "narrated",
      "obsession",
      "ominous",
      "original",
      "original plot",
      "oscar",
      "oscar (best actor)",
      "oscar (best actress)",
      "oscar (best cinematography)",
      "oscar (best directing)",
      "oscar (best effects - visual effects)",
      "oscar (best picture)",
      "oscar (best supporting actor)",
      "oscar (best supporting actress)",
      "oscar (best writing - screenplay written directly for the screen)",
      "oscar winner",
      "paranoid",
      "pg-13",
      "plot",
      "plot twist",
      "police investigation",
      "powerful ending",
      "prison",
      "prison escape",
      "psychiatrist",
      "psychiatry",
      "psychological",
      "psychology",
      "quotable",
      "realistic",
      "redemption",
      "revenge",
      "runaway",
      "scary",
      "secrets",
      "serial killer",
      "sexualized violence",
      "social commentary",
      "splatter",
      "story",
      "storytelling",
      "stylish",
      "surveillance",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thought-provoking",
      "thriller",
      "torture",
      "tricky",
      "twist",
      "twist ending",
      "twists & turns",
      "unusual plot structure",
      "vengeance",
      "very good",
      "very interesting",
      "violence",
      "violent",
      "visceral",
      "weird",
      "witty",
    ],
    title: "Silence of the Lambs, The (1991)",
    tmdbId: 274.0,
  },
  {
    genres: ["Drama", "Horror", "Mystery"],
    image: "http://image.tmdb.org/t/p/w500//4AfSDjjCy6T5LA1TMz0Lh2HlpRh.jpg",
    imdbId: 167404,
    movieId: 2762,
    rating: 4.0549989750948034,
    tags: [
      "afi 100 (movie quotes)",
      "afterlife",
      "alternate endings",
      "atmospheric",
      "bad ending",
      "based on book",
      "better than expected",
      "big budget",
      "catastrophe",
      "cerebral",
      "chase",
      "childhood",
      "cinematography",
      "classic",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "conspiracy",
      "cool",
      "corruption",
      "creepy",
      "dark",
      "death",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "earnest",
      "eerie",
      "effects",
      "emotional",
      "enigmatic",
      "entertaining",
      "excellent",
      "excellent script",
      "exceptional acting",
      "fast paced",
      "feel good movie",
      "feel-good",
      "first contact",
      "frightening",
      "fun movie",
      "ghosts",
      "ghosts/afterlife",
      "good",
      "good acting",
      "good soundtrack",
      "good story",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "happy ending",
      "heartwarming",
      "horror",
      "imdb top 250",
      "intelligent",
      "intense",
      "interesting",
      "investigation",
      "justice",
      "kids",
      "life & death",
      "light",
      "manipulation",
      "masterpiece",
      "mentor",
      "mindfuck",
      "mystery",
      "narrated",
      "nonlinear",
      "ominous",
      "original",
      "original plot",
      "oscar",
      "oscar (best actor)",
      "oscar (best actress)",
      "oscar (best directing)",
      "oscar (best effects - visual effects)",
      "oscar (best picture)",
      "oscar (best supporting actor)",
      "oscar (best supporting actress)",
      "oscar (best writing - screenplay written directly for the screen)",
      "oscar winner",
      "paranoia",
      "paranoid",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "powerful ending",
      "psychiatrist",
      "psychological",
      "psychology",
      "realistic",
      "redemption",
      "revenge",
      "runaway",
      "sad but good",
      "scary",
      "scifi",
      "secrets",
      "sentimental",
      "social commentary",
      "special effects",
      "story",
      "storytelling",
      "stunning",
      "stylized",
      "supernatural",
      "surprise ending",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thought-provoking",
      "thriller",
      "touching",
      "tricky",
      "twist",
      "twist ending",
      "twists & turns",
      "vengeance",
      "very good",
      "violence",
      "visual",
      "visually appealing",
      "visually stunning",
      "weird",
    ],
    title: "Sixth Sense, The (1999)",
    tmdbId: 745.0,
  },
  {
    genres: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
    imdbId: 482571,
    movieId: 48780,
    rating: 4.042195403318839,
    tags: [
      "19th century",
      "adaptation",
      "adapted from:book",
      "allegory",
      "alternate endings",
      "art",
      "atmospheric",
      "bad ending",
      "based on a book",
      "based on book",
      "beautiful scenery",
      "beautifully filmed",
      "betrayal",
      "better than expected",
      "big budget",
      "catastrophe",
      "cerebral",
      "chase",
      "cinematography",
      "clever",
      "clones",
      "cloning",
      "complex",
      "complicated",
      "complicated plot",
      "con men",
      "confusing",
      "conspiracy",
      "corruption",
      "costume drama",
      "creepy",
      "dark",
      "dark hero",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "eerie",
      "enigmatic",
      "ensemble cast",
      "entertaining",
      "excellent",
      "excellent script",
      "exceptional acting",
      "existentialism",
      "fantasy",
      "fantasy world",
      "fast paced",
      "forceful",
      "good",
      "good acting",
      "good soundtrack",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "happy ending",
      "harsh",
      "identity",
      "imagination",
      "imdb top 250",
      "insanity",
      "intellectual",
      "intelligent",
      "intense",
      "interesting",
      "justice",
      "life philosophy",
      "london",
      "magic",
      "manipulation",
      "masterpiece",
      "memory loss",
      "mentor",
      "mindfuck",
      "moral ambiguity",
      "movielens top pick",
      "murder",
      "mystery",
      "narrated",
      "non-linear",
      "nonlinear",
      "obsession",
      "ominous",
      "original",
      "original plot",
      "oscar (best directing)",
      "oscar winner",
      "parallel universe",
      "paranoia",
      "paranoid",
      "period piece",
      "pg-13",
      "philosophy",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "powerful ending",
      "psychological",
      "psychology",
      "redemption",
      "revenge",
      "sacrifice",
      "sci fi",
      "sci-fi",
      "science",
      "science fiction",
      "scifi",
      "secrets",
      "social commentary",
      "stage magic",
      "steampunk",
      "story",
      "storytelling",
      "stunning",
      "stylish",
      "stylized",
      "suprisingly clever",
      "surprise ending",
      "suspense",
      "suspenseful",
      "talky",
      "technology",
      "teleportation",
      "tense",
      "thought-provoking",
      "thriller",
      "tricky",
      "twist",
      "twist ending",
      "twists & turns",
      "unusual plot structure",
      "vengeance",
      "very good",
      "very interesting",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weird",
    ],
    title: "Prestige, The (2006)",
    tmdbId: 1124.0,
  },
  {
    genres: ["Action", "Adventure", "Horror", "Sci-Fi"],
    image: "http://image.tmdb.org/t/p/w500//r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
    imdbId: 90605,
    movieId: 1200,
    rating: 4.005642137763728,
    tags: [
      "action",
      "action packed",
      "adventure",
      "alien",
      "alien invasion",
      "aliens",
      "allegory",
      "androids",
      "atmospheric",
      "awesome",
      "beautiful scenery",
      "beautifully filmed",
      "big budget",
      "bleak",
      "breathtaking",
      "catastrophe",
      "cerebral",
      "chase",
      "cinematography",
      "classic",
      "claustrophobic",
      "clever",
      "complex",
      "cool",
      "crappy sequel",
      "creepy",
      "criterion",
      "cult classic",
      "cult film",
      "cyborgs",
      "dark",
      "dark hero",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "dynamic cgi action",
      "effects",
      "enigmatic",
      "entertaining",
      "epic",
      "excellent",
      "excellent script",
      "exciting",
      "existentialism",
      "fast paced",
      "fight scenes",
      "fighting",
      "first contact",
      "forceful",
      "foul language",
      "franchise",
      "frightening",
      "fun movie",
      "future",
      "futuristic",
      "giant robots",
      "good",
      "good acting",
      "good action",
      "good sequel",
      "good soundtrack",
      "good versus evil",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "gruesome",
      "gunfight",
      "guns",
      "harsh",
      "highly quotable",
      "horror",
      "imagination",
      "imdb top 250",
      "intense",
      "interesting",
      "life philosophy",
      "loneliness",
      "masterpiece",
      "melancholic",
      "mentor",
      "military",
      "monster",
      "mother-son relationship",
      "ominous",
      "original",
      "original plot",
      "oscar",
      "oscar (best actress)",
      "oscar (best directing)",
      "oscar (best effects - visual effects)",
      "oscar (best sound)",
      "oscar winner",
      "paranoid",
      "pg-13",
      "philosophy",
      "plot",
      "quotable",
      "realistic",
      "redemption",
      "sacrifice",
      "saturn award (best science fiction film)",
      "saturn award (best special effects)",
      "scary",
      "scenic",
      "sci fi",
      "sci-fi",
      "science fiction",
      "scifi",
      "scifi cult",
      "script",
      "sequel",
      "sequels",
      "series",
      "social commentary",
      "space",
      "space opera",
      "space travel",
      "special effects",
      "story",
      "storytelling",
      "suprisingly clever",
      "survival",
      "suspense",
      "suspenseful",
      "talky",
      "technology",
      "tense",
      "thriller",
      "transformation",
      "unusual plot structure",
      "vengeance",
      "very good",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weapons",
    ],
    title: "Aliens (1986)",
    tmdbId: 679.0,
  },
  {
    genres: ["Action", "Adventure", "Crime", "IMAX"],
    image: "http://image.tmdb.org/t/p/w500//hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    imdbId: 1345836,
    movieId: 91529,
    rating: 4.00020964360587,
    tags: [
      "action",
      "action packed",
      "adaptation",
      "adapted from:comic",
      "alter ego",
      "amazing cinematography",
      "anti-hero",
      "atmospheric",
      "author:alan moore",
      "awesome",
      "awesome soundtrack",
      "based on a comic",
      "based on comic",
      "batman",
      "best of 2005",
      "betrayal",
      "better than expected",
      "big budget",
      "brutality",
      "catastrophe",
      "cerebral",
      "chase",
      "cinematography",
      "clever",
      "comic book",
      "comic book adaption",
      "comics",
      "complex",
      "complicated",
      "complicated plot",
      "cool",
      "corruption",
      "crime",
      "dark",
      "dark hero",
      "dc comics",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "dynamic cgi action",
      "dystopia",
      "enigmatic",
      "epic",
      "excellent script",
      "exceptional acting",
      "exciting",
      "fast paced",
      "fight scenes",
      "fighting",
      "forceful",
      "franchise",
      "good",
      "good acting",
      "good sequel",
      "good soundtrack",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "gritty",
      "gypsy accent",
      "happy ending",
      "harsh",
      "honest",
      "imdb top 250",
      "intense",
      "interesting",
      "justice",
      "life philosophy",
      "long",
      "masterpiece",
      "mentor",
      "moral ambiguity",
      "murder",
      "mythology",
      "nocturnal",
      "original",
      "original plot",
      "oscar",
      "oscar (best directing)",
      "oscar (best supporting actor)",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "powerful ending",
      "prison escape",
      "psychological",
      "realistic",
      "redemption",
      "revenge",
      "sacrifice",
      "secrets",
      "series",
      "shallow",
      "social commentary",
      "special effects",
      "story",
      "storytelling",
      "super hero",
      "super-hero",
      "superhero",
      "superheroes",
      "suspense",
      "talky",
      "technology",
      "thriller",
      "transformation",
      "trilogy",
      "twist ending",
      "twists & turns",
      "vengeance",
      "vigilante",
      "vigilantism",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weapons",
    ],
    title: "Dark Knight Rises, The (2012)",
    tmdbId: 49026.0,
  },
  {
    genres: ["Action", "Crime", "IMAX"],
    image: "http://image.tmdb.org/t/p/w500//4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg",
    imdbId: 372784,
    movieId: 33794,
    rating: 3.970753505298084,
    tags: [
      "action",
      "action packed",
      "adaptation",
      "adapted from:comic",
      "alter ego",
      "amazing cinematography",
      "anti-hero",
      "atmospheric",
      "awesome",
      "awesome soundtrack",
      "based on a comic",
      "based on comic",
      "batman",
      "best of 2005",
      "betrayal",
      "big budget",
      "brutality",
      "chase",
      "childhood",
      "clever",
      "comic",
      "comic book",
      "comic book adaption",
      "comics",
      "complex",
      "cool",
      "corruption",
      "crime",
      "dark",
      "dark hero",
      "dc comics",
      "destiny",
      "dialogue",
      "drama",
      "dramatic",
      "dynamic cgi action",
      "earnest",
      "entertaining",
      "excellent",
      "excellent script",
      "exceptional acting",
      "exciting",
      "fast paced",
      "fight scenes",
      "fighting",
      "franchise",
      "good",
      "good acting",
      "good action",
      "good sequel",
      "good soundtrack",
      "graphic novel",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "grim",
      "gritty",
      "harsh",
      "highly quotable",
      "honest",
      "imdb top 250",
      "intense",
      "interesting",
      "justice",
      "melancholy",
      "mentor",
      "moral ambiguity",
      "movielens top pick",
      "murder",
      "mutants",
      "mythology",
      "ninja",
      "nocturnal",
      "original",
      "original plot",
      "oscar",
      "oscar (best directing)",
      "oscar (best effects - visual effects)",
      "oscar winner",
      "pg-13",
      "plot",
      "plot twist",
      "prequel",
      "psychological",
      "psychology",
      "realistic",
      "realistic action",
      "redemption",
      "revenge",
      "runaway",
      "sacrifice",
      "samurai",
      "series",
      "shallow",
      "social commentary",
      "special effects",
      "story",
      "storytelling",
      "stylish",
      "stylized",
      "super hero",
      "super-hero",
      "superhero",
      "superheroes",
      "suspense",
      "technology",
      "thriller",
      "transformation",
      "vengeance",
      "very good",
      "vigilante",
      "vigilantism",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weapons",
    ],
    title: "Batman Begins (2005)",
    tmdbId: 272.0,
  },
  {
    genres: ["Drama", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//lv5xShBIDPe7m4ufdlV0IAc7Avk.jpg",
    imdbId: 2267998,
    movieId: 112556,
    rating: 3.9364435429344153,
    tags: [
      "adaptation",
      "adapted from:book",
      "adultery",
      "alternate endings",
      "atmospheric",
      "bad ending",
      "based on a book",
      "based on book",
      "bdsm",
      "betrayal",
      "brutality",
      "catastrophe",
      "cerebral",
      "chase",
      "cheating",
      "cinematography",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "conspiracy",
      "corruption",
      "creepy",
      "crime",
      "dark",
      "dark humor",
      "detective",
      "dialogue",
      "disturbing",
      "drama",
      "dramatic",
      "enigmatic",
      "entertaining",
      "excellent",
      "excellent script",
      "exceptional acting",
      "fast paced",
      "good",
      "good acting",
      "good soundtrack",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "guilt",
      "identity",
      "imdb top 250",
      "infidelity",
      "insanity",
      "intellectual",
      "intelligent",
      "intense",
      "interesting",
      "investigation",
      "justice",
      "kidnapping",
      "lawyer",
      "lawyers",
      "manipulation",
      "marriage",
      "masterpiece",
      "mentor",
      "mindfuck",
      "moral ambiguity",
      "murder",
      "murder mystery",
      "mystery",
      "narrated",
      "neo-noir",
      "nonlinear",
      "obsession",
      "ominous",
      "original",
      "oscar",
      "oscar (best actress)",
      "oscar (best cinematography)",
      "oscar (best directing)",
      "oscar (best picture)",
      "oscar (best supporting actor)",
      "oscar (best supporting actress)",
      "oscar winner",
      "paranoia",
      "paranoid",
      "perfect",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "powerful ending",
      "pregnancy",
      "psychological",
      "psychology",
      "revenge",
      "runaway",
      "secrets",
      "serial killer",
      "social commentary",
      "story",
      "storytelling",
      "stylish",
      "stylized",
      "suprisingly clever",
      "surprise ending",
      "surreal",
      "surveillance",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thought-provoking",
      "thriller",
      "tricky",
      "twist",
      "twist ending",
      "twists & turns",
      "unusual plot structure",
      "vengeance",
      "very interesting",
      "violence",
      "violent",
      "visually appealing",
      "visually stunning",
      "weird",
    ],
    title: "Gone Girl (2014)",
    tmdbId: 210577.0,
  },
  {
    genres: ["Drama", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    imdbId: 1392214,
    movieId: 104879,
    rating: 3.9212290502793294,
    tags: [
      "allegory",
      "alternate endings",
      "amazing cinematography",
      "assassination",
      "atmospheric",
      "bad ending",
      "bleak",
      "brutal",
      "brutality",
      "catastrophe",
      "cerebral",
      "character study",
      "chase",
      "cinematography",
      "clever",
      "complex",
      "complex characters",
      "complicated",
      "complicated plot",
      "conspiracy",
      "corruption",
      "creepy",
      "crime",
      "culture clash",
      "dark",
      "detective",
      "dialogue",
      "disturbing",
      "drama",
      "dramatic",
      "emotional",
      "enigmatic",
      "excellent",
      "excellent script",
      "exceptional acting",
      "family",
      "fast paced",
      "forceful",
      "good",
      "good acting",
      "good soundtrack",
      "great",
      "great acting",
      "great cinematography",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "gritty",
      "guilt",
      "harsh",
      "hospital",
      "imdb top 250",
      "insanity",
      "intelligent",
      "intense",
      "interesting",
      "investigation",
      "justice",
      "kidnapping",
      "masterpiece",
      "maze",
      "mental illness",
      "mentor",
      "mindfuck",
      "moral ambiguity",
      "morality",
      "movielens top pick",
      "murder",
      "murder mystery",
      "mystery",
      "obsession",
      "original",
      "original plot",
      "oscar",
      "oscar (best actress)",
      "oscar (best cinematography)",
      "oscar (best directing)",
      "oscar winner",
      "paranoia",
      "pg-13",
      "photography",
      "plot",
      "plot holes",
      "plot twist",
      "police",
      "police corruption",
      "police investigation",
      "pornography",
      "powerful ending",
      "prison",
      "psychological",
      "psychology",
      "realistic",
      "redemption",
      "revenge",
      "runaway",
      "sacrifice",
      "secrets",
      "serial killer",
      "slow",
      "slow paced",
      "social commentary",
      "story",
      "storytelling",
      "surprise ending",
      "surveillance",
      "survival",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thought-provoking",
      "thriller",
      "torture",
      "tragedy",
      "twist",
      "twist ending",
      "twists & turns",
      "underrated",
      "unusual plot structure",
      "vengeance",
      "very interesting",
      "vigilante",
      "vigilantism",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "weird",
    ],
    title: "Prisoners (2013)",
    tmdbId: 146233.0,
  },
  {
    genres: ["Action", "Adventure", "Sci-Fi"],
    image: "http://image.tmdb.org/t/p/w500//78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    imdbId: 371746,
    movieId: 59315,
    rating: 3.913052578700603,
    tags: [
      "action",
      "action packed",
      "adaptation",
      "adapted from:comic",
      "adventure",
      "alter ego",
      "anti-hero",
      "apocalypse",
      "arms dealer",
      "awesome",
      "bad cgi",
      "based on a comic",
      "based on comic",
      "betrayal",
      "better than expected",
      "big budget",
      "california",
      "catastrophe",
      "cgi",
      "chase",
      "clever",
      "comedy",
      "comic",
      "comic book",
      "comic book adaption",
      "comics",
      "cool",
      "corruption",
      "dark hero",
      "dc comics",
      "destiny",
      "dialogue",
      "dynamic cgi action",
      "effects",
      "entertaining",
      "excellent",
      "exciting",
      "fast paced",
      "fight scenes",
      "fighting",
      "franchise",
      "fun",
      "fun movie",
      "funny",
      "futuristic",
      "giant robots",
      "good",
      "good acting",
      "good action",
      "good soundtrack",
      "good versus evil",
      "graphic novel",
      "great",
      "great acting",
      "great dialogue",
      "great ending",
      "great movie",
      "humor",
      "humorous",
      "imdb top 250",
      "inspiring",
      "intense",
      "interesting",
      "justice",
      "life philosophy",
      "marvel",
      "mentor",
      "military",
      "murder",
      "mutants",
      "mythology",
      "nocturnal",
      "original",
      "original plot",
      "oscar winner",
      "pg-13",
      "plot",
      "product placement",
      "realistic",
      "realistic action",
      "redemption",
      "revenge",
      "robert downey jr",
      "robots",
      "sacrifice",
      "sci fi",
      "sci-fi",
      "science fiction",
      "script",
      "sequel",
      "sequels",
      "shallow",
      "special effects",
      "story",
      "storytelling",
      "super hero",
      "super-hero",
      "superhero",
      "superheroes",
      "technology",
      "terrorism",
      "thriller",
      "torture",
      "transformation",
      "vengeance",
      "very good",
      "vigilante",
      "vigilantism",
      "violence",
      "violent",
      "visual",
      "visually appealing",
      "visually stunning",
      "visuals",
      "watch the credits",
      "weapons",
      "witty",
    ],
    title: "Iron Man (2008)",
    tmdbId: 1726.0,
  },
  {
    genres: ["Action", "Horror", "Sci-Fi", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//tzGY49kseSE9QAKk47uuDGwnSCu.jpg",
    imdbId: 84787,
    movieId: 2288,
    rating: 3.796949865607105,
    tags: [
      "alien",
      "alien invasion",
      "aliens",
      "allegory",
      "antarctica",
      "apocalypse",
      "atmospheric",
      "bleak",
      "blood",
      "bloody",
      "brutality",
      "chase",
      "cinematography",
      "classic",
      "claustrophobic",
      "clever",
      "creepy",
      "cult",
      "cult classic",
      "cult film",
      "dark",
      "dialogue",
      "downbeat",
      "eerie",
      "effects",
      "ensemble cast",
      "excellent script",
      "first contact",
      "frightening",
      "good",
      "good acting",
      "good soundtrack",
      "gore",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "gruesome",
      "gunfight",
      "highly quotable",
      "horror",
      "imdb top 250",
      "intense",
      "interesting",
      "isolation",
      "lone hero",
      "loneliness",
      "masterpiece",
      "monster",
      "monsters",
      "ominous",
      "original",
      "original plot",
      "oscar (best directing)",
      "paranoia",
      "paranoid",
      "powerful ending",
      "psychological",
      "quotable",
      "scary",
      "sci fi",
      "sci-fi",
      "science fiction",
      "scifi",
      "social commentary",
      "special effects",
      "splatter",
      "story",
      "storytelling",
      "suprisingly clever",
      "survival",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "transformation",
      "violence",
      "violent",
      "visceral",
      "visual",
      "weapons",
      "weird",
    ],
    title: "Thing, The (1982)",
    tmdbId: 1091.0,
  },
  {
    genres: ["Drama", "Horror", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//m9o1oQrCBgL3EnvCqBr7xQ2Haco.jpg",
    imdbId: 117883,
    movieId: 5570,
    rating: 3.770096463022508,
    tags: [
      "allegory",
      "assassination",
      "atmospheric",
      "bloody",
      "brutal",
      "brutality",
      "cerebral",
      "chase",
      "cinematography",
      "claustrophobic",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "conspiracy",
      "creepy",
      "criterion",
      "cult classic",
      "cult film",
      "dark",
      "dark humor",
      "death",
      "dialogue",
      "disturbing",
      "enigmatic",
      "excellent script",
      "foreign",
      "frightening",
      "golden palm",
      "good",
      "good acting",
      "good soundtrack",
      "gory",
      "great",
      "great acting",
      "great ending",
      "greed",
      "grim",
      "gruesome",
      "harsh",
      "hitchcock",
      "identity",
      "imdb top 250",
      "intense",
      "interesting",
      "investigation",
      "macabre",
      "manipulation",
      "mentor",
      "mindfuck",
      "murder",
      "murder mystery",
      "mystery",
      "obsession",
      "ominous",
      "original",
      "paranoia",
      "paranoid",
      "plot",
      "plot twist",
      "police investigation",
      "pornography",
      "powerful ending",
      "psychological",
      "psychology",
      "pulp",
      "revenge",
      "runaway",
      "scary",
      "secrets",
      "serial killer",
      "sexualized violence",
      "social commentary",
      "spain",
      "spanish",
      "splatter",
      "storytelling",
      "stylish",
      "stylized",
      "surprise ending",
      "suspense",
      "suspenseful",
      "tense",
      "thriller",
      "torture",
      "twist",
      "twist ending",
      "twists & turns",
      "vengeance",
      "very interesting",
      "violence",
      "violent",
      "visceral",
      "visually appealing",
      "voyeurism",
      "weird",
    ],
    title: "Thesis (Tesis) (1996)",
    tmdbId: 9299.0,
  },
  {
    genres: ["Crime", "Drama", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//6YmeO4pB7XTh8P8F960O1uA14JO.jpg",
    imdbId: 443706,
    movieId: 51540,
    rating: 3.675454312771948,
    tags: [
      "1970s",
      "adaptation",
      "amazing photography",
      "atmospheric",
      "bad ending",
      "based on a book",
      "based on a true story",
      "based on book",
      "based on true story",
      "brutality",
      "california",
      "catastrophe",
      "cerebral",
      "character study",
      "chase",
      "cinematography",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "conspiracy",
      "corruption",
      "creepy",
      "crime",
      "criterion",
      "dark",
      "detective",
      "dialogue",
      "disturbing",
      "downbeat",
      "drama",
      "dramatic",
      "enigmatic",
      "factual",
      "good",
      "good acting",
      "good soundtrack",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "guilt",
      "identity",
      "imdb top 250",
      "intense",
      "interesting",
      "investigation",
      "justice",
      "long",
      "manipulation",
      "moral ambiguity",
      "murder",
      "murder mystery",
      "mystery",
      "obsession",
      "original",
      "oscar (best actress)",
      "oscar (best directing)",
      "paranoia",
      "plot",
      "police",
      "police corruption",
      "police investigation",
      "pornography",
      "psychological",
      "psychology",
      "realistic",
      "robert downey jr",
      "runaway",
      "san francisco",
      "secrets",
      "serial killer",
      "slow",
      "slow paced",
      "social commentary",
      "story",
      "storytelling",
      "stylish",
      "stylized",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thriller",
      "too long",
      "torture",
      "true story",
      "twist",
      "twist ending",
      "twists & turns",
      "unusual plot structure",
      "vengeance",
      "very interesting",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "weird",
    ],
    title: "Zodiac (2007)",
    tmdbId: 1949.0,
  },
  {
    genres: ["Crime", "Drama", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//yBXrSxXoGkyexS3ysUOxEpE2P94.jpg",
    imdbId: 264616,
    movieId: 5294,
    rating: 3.665573770491803,
    tags: [
      "atmospheric",
      "bad ending",
      "biblical",
      "brainwashing",
      "brothers",
      "brutality",
      "cerebral",
      "chase",
      "child abuse",
      "childhood",
      "cinematography",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "corruption",
      "creepy",
      "crime",
      "dark",
      "demons",
      "dialogue",
      "directorial debut",
      "disturbing",
      "drama",
      "eerie",
      "excellent",
      "excellent script",
      "exceptional acting",
      "fast paced",
      "first contact",
      "god",
      "good",
      "good acting",
      "good soundtrack",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "guilt",
      "horror",
      "identity",
      "imagination",
      "imdb top 250",
      "insanity",
      "intense",
      "interesting",
      "islam",
      "justice",
      "mental illness",
      "mentor",
      "mindfuck",
      "mission from god",
      "moody",
      "moral ambiguity",
      "murder",
      "narrated",
      "ominous",
      "original",
      "original plot",
      "oscar (best directing)",
      "paranoia",
      "paranoid",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "powerful ending",
      "predictable",
      "psychological",
      "psychology",
      "redemption",
      "religion",
      "revenge",
      "secrets",
      "serial killer",
      "single father",
      "social commentary",
      "splatter",
      "story",
      "storytelling",
      "stylized",
      "supernatural",
      "surprise ending",
      "surreal",
      "surveillance",
      "suspense",
      "suspenseful",
      "tense",
      "thought-provoking",
      "thriller",
      "torture",
      "twist",
      "twist ending",
      "twists & turns",
      "vengeance",
      "very good",
      "very interesting",
      "violence",
      "violent",
      "visceral",
      "visual",
      "visually appealing",
      "visually stunning",
      "weird",
    ],
    title: "Frailty (2001)",
    tmdbId: 12149.0,
  },
  {
    genres: ["Horror", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//1YINof6kN5yRdePEbcU5360ejoq.jpg",
    imdbId: 178868,
    movieId: 6242,
    rating: 3.618703631393987,
    tags: [
      "adaptation",
      "atmospheric",
      "better than the american version",
      "blood",
      "brutality",
      "claustrophobic",
      "creepy",
      "cult classic",
      "cult film",
      "dark",
      "death",
      "demons",
      "dialogue",
      "disturbing",
      "downbeat",
      "eerie",
      "enigmatic",
      "frightening",
      "ghosts",
      "good",
      "good acting",
      "good soundtrack",
      "gory",
      "great ending",
      "grim",
      "gruesome",
      "horror",
      "intense",
      "interesting",
      "investigation",
      "japan",
      "japanese",
      "macabre",
      "mystery",
      "ominous",
      "original",
      "original plot",
      "police investigation",
      "psychological",
      "psychology",
      "scary",
      "social commentary",
      "splatter",
      "story",
      "storytelling",
      "strange",
      "supernatural",
      "suspense",
      "suspenseful",
      "talky",
      "tense",
      "thriller",
      "tokyo",
      "transformation",
      "twist",
      "twist ending",
      "visceral",
      "visual",
      "visually appealing",
      "weird",
    ],
    title: "Ringu (Ring) (1998)",
    tmdbId: 2671.0,
  },
  {
    genres: ["Comedy", "Horror", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//jPKEeHmUuoDnIaRs6VUqSr4qRGR.jpg",
    imdbId: 3504048,
    movieId: 113252,
    rating: 3.6125,
    tags: [
      "adaptation",
      "atmospheric",
      "black comedy",
      "blood",
      "bloody",
      "brutality",
      "chase",
      "childhood",
      "cinematography",
      "clever",
      "comedy",
      "complex",
      "creepy",
      "cult classic",
      "dark",
      "dark comedy",
      "dark humor",
      "drinking",
      "family drama",
      "forceful",
      "fun movie",
      "ghosts",
      "good acting",
      "good soundtrack",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "haunted house",
      "horror",
      "humorous",
      "intense",
      "murder",
      "murder mystery",
      "new zealand",
      "original",
      "plot twist",
      "police investigation",
      "psychological",
      "sacrifice",
      "scary",
      "secrets",
      "sexualized violence",
      "social commentary",
      "splatter",
      "story",
      "supernatural",
      "suspense",
      "suspenseful",
      "tense",
      "thriller",
      "transformation",
      "twist",
      "twist ending",
      "twists & turns",
      "unlikeable characters",
      "violence",
      "violent",
      "visceral",
      "visually appealing",
      "weird",
    ],
    title: "Housebound (2014)",
    tmdbId: 253306.0,
  },
  {
    genres: ["Crime", "Horror", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//bnidwEvWNAVJ3Uco9wWtuzWAfrx.jpg",
    imdbId: 309698,
    movieId: 6323,
    rating: 3.583606893721789,
    tags: [
      "absurd",
      "alternate endings",
      "atmospheric",
      "bad ending",
      "catastrophe",
      "chase",
      "claustrophobic",
      "clever",
      "complex",
      "complicated",
      "complicated plot",
      "confusing",
      "conspiracy",
      "corruption",
      "creativity",
      "creepy",
      "dark",
      "death",
      "destiny",
      "dialogue",
      "eerie",
      "enigmatic",
      "ensemble cast",
      "excellent",
      "fast paced",
      "good",
      "good acting",
      "good soundtrack",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "horror",
      "hotel",
      "identity",
      "indians",
      "insanity",
      "intense",
      "interesting",
      "investigation",
      "manipulation",
      "mindfuck",
      "murder",
      "murder mystery",
      "mystery",
      "ominous",
      "original",
      "original plot",
      "paranoia",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "predictable",
      "psychiatrist",
      "psychiatry",
      "psychological",
      "psychology",
      "revenge",
      "scary",
      "secrets",
      "serial killer",
      "story",
      "storytelling",
      "stranded",
      "supernatural",
      "surprise ending",
      "surreal",
      "survival",
      "suspense",
      "suspenseful",
      "tense",
      "thought-provoking",
      "thriller",
      "tricky",
      "twist",
      "twist ending",
      "twists & turns",
      "underrated",
      "vengeance",
      "very good",
      "very interesting",
      "violence",
      "weird",
    ],
    title: "Identity (2003)",
    tmdbId: 2832.0,
  },
  {
    genres: ["Horror", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//p0LcWxOIoBx0MEZMn8tFcrvDXR1.jpg",
    imdbId: 75005,
    movieId: 1350,
    rating: 3.556273062730628,
    tags: [
      "adaptation",
      "adoption",
      "apocalypse",
      "atmospheric",
      "based on a book",
      "biblical",
      "blood",
      "bloody",
      "brutality",
      "catholicism",
      "christianity",
      "cinematography",
      "classic",
      "creepy",
      "cult",
      "cult classic",
      "cult film",
      "dark",
      "death",
      "demons",
      "devil",
      "dialogue",
      "disturbing",
      "eerie",
      "effects",
      "excellent",
      "family drama",
      "frightening",
      "good",
      "good acting",
      "good soundtrack",
      "good versus evil",
      "gory",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "greed",
      "grim",
      "gruesome",
      "horror",
      "hospital",
      "imdb top 250",
      "intense",
      "macabre",
      "masterpiece",
      "murder",
      "ominous",
      "original",
      "original plot",
      "oscar (best effects - visual effects)",
      "psychological",
      "psychology",
      "religion",
      "runaway",
      "scary",
      "serial killer",
      "sexualized violence",
      "story",
      "storytelling",
      "supernatural",
      "suspense",
      "suspenseful",
      "tense",
      "transformation",
      "vengeance",
      "violence",
      "violent",
      "visceral",
      "visually appealing",
      "weird",
      "world politics",
    ],
    title: "Omen, The (1976)",
    tmdbId: 794.0,
  },
  {
    genres: ["Horror", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//rLNSOudrayDBo1uqXjrhxcjODIC.jpg",
    imdbId: 387564,
    movieId: 8957,
    rating: 3.4669939989088925,
    tags: [
      "alternate endings",
      "atmospheric",
      "bad acting",
      "bad ending",
      "blood",
      "bloody",
      "brutal",
      "brutality",
      "claustrophobic",
      "clever",
      "creativity",
      "creepy",
      "cult classic",
      "cult film",
      "dark",
      "detective",
      "dialogue",
      "disturbing",
      "doctors",
      "excellent script",
      "exceptional acting",
      "fast paced",
      "franchise",
      "good",
      "good acting",
      "good soundtrack",
      "gore",
      "gory",
      "gratuitous violence",
      "great",
      "great acting",
      "great ending",
      "great movie",
      "gruesome",
      "horror",
      "insanity",
      "intense",
      "interesting",
      "kidnapping",
      "life & death",
      "low budget",
      "macabre",
      "mindfuck",
      "murder",
      "original",
      "original plot",
      "pg-13",
      "plot",
      "plot holes",
      "plot twist",
      "police investigation",
      "powerful ending",
      "psychological",
      "psychology",
      "revenge",
      "scary",
      "secrets",
      "serial killer",
      "sexualized violence",
      "slasher",
      "splatter",
      "story",
      "storytelling",
      "stylish",
      "surprise ending",
      "survival",
      "suspense",
      "suspenseful",
      "tense",
      "thriller",
      "torture",
      "twist",
      "twist ending",
      "twists & turns",
      "vengeance",
      "violence",
      "violent",
      "visceral",
      "weird",
    ],
    title: "Saw (2004)",
    tmdbId: 176.0,
  },
  {
    genres: ["Horror", "Mystery", "Thriller"],
    image: "http://image.tmdb.org/t/p/w500//gghD2ZIPjMzLnnBuT3AZQGYnIW9.jpg",
    imdbId: 298130,
    movieId: 5679,
    rating: 3.4264026055894097,
    tags: [
      "alternate endings",
      "atmospheric",
      "bad ending",
      "better than the american version",
      "blood",
      "chase",
      "cinematography",
      "clever",
      "creepy",
      "cult classic",
      "dark",
      "death",
      "demons",
      "dialogue",
      "disturbing",
      "eerie",
      "effects",
      "frightening",
      "ghosts",
      "good",
      "good acting",
      "gory",
      "great",
      "great ending",
      "great movie",
      "horror",
      "intense",
      "interesting",
      "investigation",
      "macabre",
      "mother-son relationship",
      "mystery",
      "ominous",
      "original",
      "original plot",
      "pg-13",
      "plot holes",
      "plot twist",
      "psychological",
      "psychology",
      "remake",
      "scary",
      "sexualized violence",
      "special effects",
      "splatter",
      "story",
      "storytelling",
      "supernatural",
      "surprise ending",
      "suspense",
      "suspenseful",
      "tense",
      "thriller",
      "twist",
      "twist ending",
      "twists & turns",
      "violence",
      "visceral",
      "visual",
      "visually appealing",
      "weird",
    ],
    title: "Ring, The (2002)",
    tmdbId: 565.0,
  },
]
